Feature/table component
JoseCortezz25/trinity pull request #21
Opened 2022-10-19 23:24 UTC by JoseCortezz25

@JoseCortezz25  closes #11

2022-10-20 01:51 UTC, Juanestban commented
You should put in this description from pr something like this

**Example:**
# Issues
Closes #11

2022-10-20 02:02 UTC, Juanestban requested changes
LGTM

Just you'll need make refactor

2022-10-20 02:02 UTC, Juanestban commented on src/routes/routes.jsx
> +            <Route path="/admin/usuarios" element={<Users />}/>
You could have a Array where have an 

- Component page
- path
- index `boolean | undefined`

2022-10-20 02:02 UTC, Juanestban commented on src/pages/Admin/Syllabus/Syllabus.jsx
> +        columns={5}
Remove this

2022-10-20 02:02 UTC, Juanestban commented on src/pages/Admin/Resources/Resources.jsx
> +        {RecommendedResources.map((resource) => (
Try to desestucture this param

```suggestion
        {RecommendedResources.map(({ title, type, link, actions }) => (
```

2022-10-20 02:02 UTC, Juanestban commented on src/pages/Admin/Resources/Resources.jsx
> +            <li>{resource.title}</li>
Try follow the same example

```suggestion
            <li>{title}</li>
```

2022-10-20 02:02 UTC, Juanestban commented on src/pages/Admin/LearningPath/LearningPath.jsx
> +        {LearningPaths.map((path) => (
Same of above

2022-10-20 02:02 UTC, Juanestban commented on src/pages/Admin/LearningPath/LearningPath.jsx
> +            <li>{path.title}</li>
Same of above

2022-10-20 02:02 UTC, Juanestban commented on src/pages/Admin/Content/Content.jsx
> +        {Contents.map((path) => (
Same of above

2022-10-20 02:02 UTC, Juanestban commented on src/pages/Admin/Content/Content.jsx
> +            <li className="TextClipped">{path.link}</li>
Same of above

2022-10-20 02:02 UTC, Juanestban commented on src/components/Table/Table.jsx
> +const Table = ({ columns, headers, children }) => {
Remove prop `columns` and try use default params

```suggestion
const Table = ({ headers = [], children }) => {
```

2022-10-20 16:47 UTC, JoseCortezz25 commented
Suggestions have been developed. @Juanestban

2022-10-23 03:37 UTC, Juanestban commented
LGTM 💯 but remenber change the branch `master` because this should be merged to `dev` branch

2022-10-23 03:38 UTC, Juanestban approved these changes

2022-10-24 21:24 UTC, Juanestban commented
and try to resolve the conflict  (don't worry, if you need help about this conflict, call me @Juanestban and I'll try to help you)

2022-10-25 16:26 UTC, merged